spring.application.name=order-proxy
base.url=http://localhost:8081/orders
server.port=8080
rest-client.connect-timeout=3000
rest-client.read-timeout=3000
rest-client.max-attempts=3
rest-client.backoff-delay=1000